services:
  - type: web
    name: web-kachki-server
    env: java
    buildCommand: cd web-kachki-server/server && ./mvnw clean package -DskipTests
    startCommand: cd web-kachki-server/server && java -jar target/web-kachki-server-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: JAVA_VERSION
        value: 17
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GCP_CREDENTIALS_LOCATION
        sync: false
      - key: GCS_BUCKET_VIDEO
        value: video-kachki
      - key: GCS_BUCKET_PHOTO
        value: photo-kachki
      - key: GCP_PROJECT_ID
        value: web-kachki

